---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "stockinfo-config"
  namespace: "itdays"
  labels:
    app: "stockinfo"
data:
  STOCKINFO_LISTEN_ADDR: ":3001"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "stockinfo"
  namespace: "itdays"
  labels:
    app: "stockinfo"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "stockinfo"
  template:
    metadata:
      labels:
        app: "stockinfo"
    spec:
      containers:
      - name: "microservice-stockinfo"
        image: "gcr.io/itdays-201118/microservice-stockinfo:latest"
        env:
        - name: "STOCKINFO_LISTEN_ADDR"
          valueFrom:
            configMapKeyRef:
              key: "STOCKINFO_LISTEN_ADDR"
              name: "stockinfo-config"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "stockinfo-hpa"
  namespace: "itdays"
  labels:
    app: "stockinfo"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "stockinfo"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
