// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stockinfo.proto

package stockinfo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StockInfoRequest struct {
	Stockname            string   `protobuf:"bytes,1,opt,name=stockname,proto3" json:"stockname,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Resolution           int32    `protobuf:"varint,4,opt,name=resolution,proto3" json:"resolution,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockInfoRequest) Reset()         { *m = StockInfoRequest{} }
func (m *StockInfoRequest) String() string { return proto.CompactTextString(m) }
func (*StockInfoRequest) ProtoMessage()    {}
func (*StockInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockinfo_82bb7d2486e17029, []int{0}
}
func (m *StockInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockInfoRequest.Unmarshal(m, b)
}
func (m *StockInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockInfoRequest.Marshal(b, m, deterministic)
}
func (dst *StockInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockInfoRequest.Merge(dst, src)
}
func (m *StockInfoRequest) XXX_Size() int {
	return xxx_messageInfo_StockInfoRequest.Size(m)
}
func (m *StockInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockInfoRequest proto.InternalMessageInfo

func (m *StockInfoRequest) GetStockname() string {
	if m != nil {
		return m.Stockname
	}
	return ""
}

func (m *StockInfoRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *StockInfoRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *StockInfoRequest) GetResolution() int32 {
	if m != nil {
		return m.Resolution
	}
	return 0
}

type Indicator struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Indicator) Reset()         { *m = Indicator{} }
func (m *Indicator) String() string { return proto.CompactTextString(m) }
func (*Indicator) ProtoMessage()    {}
func (*Indicator) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockinfo_82bb7d2486e17029, []int{1}
}
func (m *Indicator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Indicator.Unmarshal(m, b)
}
func (m *Indicator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Indicator.Marshal(b, m, deterministic)
}
func (dst *Indicator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Indicator.Merge(dst, src)
}
func (m *Indicator) XXX_Size() int {
	return xxx_messageInfo_Indicator.Size(m)
}
func (m *Indicator) XXX_DiscardUnknown() {
	xxx_messageInfo_Indicator.DiscardUnknown(m)
}

var xxx_messageInfo_Indicator proto.InternalMessageInfo

func (m *Indicator) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Indicator) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type StockInfoResponse struct {
	Stockname            string       `protobuf:"bytes,1,opt,name=stockname,proto3" json:"stockname,omitempty"`
	PriceData            []*Indicator `protobuf:"bytes,2,rep,name=PriceData,proto3" json:"PriceData,omitempty"`
	VolumeData           []*Indicator `protobuf:"bytes,3,rep,name=VolumeData,proto3" json:"VolumeData,omitempty"`
	MacdData             []*Indicator `protobuf:"bytes,4,rep,name=MacdData,proto3" json:"MacdData,omitempty"`
	RsiData              []*Indicator `protobuf:"bytes,5,rep,name=RsiData,proto3" json:"RsiData,omitempty"`
	CciData              []*Indicator `protobuf:"bytes,6,rep,name=CciData,proto3" json:"CciData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StockInfoResponse) Reset()         { *m = StockInfoResponse{} }
func (m *StockInfoResponse) String() string { return proto.CompactTextString(m) }
func (*StockInfoResponse) ProtoMessage()    {}
func (*StockInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stockinfo_82bb7d2486e17029, []int{2}
}
func (m *StockInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockInfoResponse.Unmarshal(m, b)
}
func (m *StockInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockInfoResponse.Marshal(b, m, deterministic)
}
func (dst *StockInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockInfoResponse.Merge(dst, src)
}
func (m *StockInfoResponse) XXX_Size() int {
	return xxx_messageInfo_StockInfoResponse.Size(m)
}
func (m *StockInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockInfoResponse proto.InternalMessageInfo

func (m *StockInfoResponse) GetStockname() string {
	if m != nil {
		return m.Stockname
	}
	return ""
}

func (m *StockInfoResponse) GetPriceData() []*Indicator {
	if m != nil {
		return m.PriceData
	}
	return nil
}

func (m *StockInfoResponse) GetVolumeData() []*Indicator {
	if m != nil {
		return m.VolumeData
	}
	return nil
}

func (m *StockInfoResponse) GetMacdData() []*Indicator {
	if m != nil {
		return m.MacdData
	}
	return nil
}

func (m *StockInfoResponse) GetRsiData() []*Indicator {
	if m != nil {
		return m.RsiData
	}
	return nil
}

func (m *StockInfoResponse) GetCciData() []*Indicator {
	if m != nil {
		return m.CciData
	}
	return nil
}

func init() {
	proto.RegisterType((*StockInfoRequest)(nil), "StockInfoRequest")
	proto.RegisterType((*Indicator)(nil), "Indicator")
	proto.RegisterType((*StockInfoResponse)(nil), "StockInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StockInfoServiceClient is the client API for StockInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StockInfoServiceClient interface {
	StockInfo(ctx context.Context, in *StockInfoRequest, opts ...grpc.CallOption) (*StockInfoResponse, error)
}

type stockInfoServiceClient struct {
	cc *grpc.ClientConn
}

func NewStockInfoServiceClient(cc *grpc.ClientConn) StockInfoServiceClient {
	return &stockInfoServiceClient{cc}
}

func (c *stockInfoServiceClient) StockInfo(ctx context.Context, in *StockInfoRequest, opts ...grpc.CallOption) (*StockInfoResponse, error) {
	out := new(StockInfoResponse)
	err := c.cc.Invoke(ctx, "/StockInfoService/StockInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockInfoServiceServer is the server API for StockInfoService service.
type StockInfoServiceServer interface {
	StockInfo(context.Context, *StockInfoRequest) (*StockInfoResponse, error)
}

func RegisterStockInfoServiceServer(s *grpc.Server, srv StockInfoServiceServer) {
	s.RegisterService(&_StockInfoService_serviceDesc, srv)
}

func _StockInfoService_StockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockInfoServiceServer).StockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StockInfoService/StockInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockInfoServiceServer).StockInfo(ctx, req.(*StockInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StockInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StockInfoService",
	HandlerType: (*StockInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StockInfo",
			Handler:    _StockInfoService_StockInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stockinfo.proto",
}

func init() { proto.RegisterFile("stockinfo.proto", fileDescriptor_stockinfo_82bb7d2486e17029) }

var fileDescriptor_stockinfo_82bb7d2486e17029 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0xbd, 0xeb, 0xf5, 0xb4, 0xcf, 0xc1, 0xbb, 0x87, 0x43, 0x11, 0x11, 0x29, 0x22, 0xc5,
	0xa1, 0xc3, 0xe9, 0xee, 0xa0, 0x83, 0x37, 0x08, 0x92, 0x03, 0xf7, 0xd8, 0x46, 0x08, 0x5e, 0x93,
	0x9a, 0xa4, 0x87, 0xff, 0xbb, 0x8b, 0x69, 0x72, 0xb6, 0xc5, 0x0c, 0x6e, 0xcd, 0xf7, 0xfd, 0xc8,
	0xfb, 0xd1, 0x17, 0x38, 0xd1, 0x46, 0x96, 0x1f, 0x5c, 0xbc, 0xcb, 0xa2, 0x51, 0xd2, 0xc8, 0xec,
	0x0b, 0x16, 0x9b, 0x2e, 0x5a, 0xdb, 0x88, 0xb0, 0xcf, 0x96, 0x69, 0x83, 0xe7, 0x90, 0x38, 0x4c,
	0xd0, 0x9a, 0xa5, 0x93, 0xcb, 0x49, 0x9e, 0x90, 0x21, 0xc0, 0x53, 0x88, 0xb5, 0xa1, 0xca, 0xa4,
	0x53, 0xdb, 0x44, 0xc4, 0x1f, 0x70, 0x01, 0x11, 0x13, 0x55, 0x1a, 0xb9, 0xac, 0xfb, 0xc4, 0x0b,
	0x00, 0xc5, 0xb4, 0xdc, 0xb6, 0x86, 0x4b, 0x91, 0xce, 0x6c, 0x11, 0x93, 0x51, 0x92, 0xdd, 0x43,
	0xb2, 0x16, 0x15, 0x2f, 0xa9, 0x91, 0xaa, 0xbb, 0x74, 0x47, 0xb7, 0xad, 0x1f, 0x37, 0x25, 0xfe,
	0xd0, 0x89, 0x18, 0x5e, 0x5b, 0x25, 0x5a, 0x37, 0xfb, 0x71, 0x43, 0x90, 0x7d, 0x4f, 0x60, 0x39,
	0x72, 0xd7, 0x8d, 0x14, 0x9a, 0xfd, 0x23, 0x9f, 0x43, 0xf2, 0xa2, 0x78, 0xc9, 0x1e, 0xa9, 0xa1,
	0xf6, 0xc6, 0x28, 0x3f, 0x5e, 0x41, 0xd1, 0x6b, 0x90, 0xa1, 0xc4, 0x1b, 0x80, 0x57, 0xab, 0x5a,
	0x7b, 0x34, 0x0a, 0xd0, 0x51, 0x8b, 0xd7, 0x70, 0xf4, 0x4c, 0xcb, 0xca, 0x91, 0xb3, 0x80, 0xec,
	0x3b, 0xbc, 0x82, 0x43, 0xa2, 0xb9, 0xc3, 0xe2, 0x00, 0xfb, 0xad, 0x3a, 0xea, 0xa1, 0xf4, 0xd4,
	0x3c, 0xa4, 0xf6, 0xd5, 0xea, 0x69, 0xb4, 0xb8, 0x0d, 0x53, 0x3b, 0xeb, 0x8d, 0x77, 0x90, 0xf4,
	0x19, 0x2e, 0x8b, 0xbf, 0x8b, 0x3d, 0xc3, 0x22, 0xf8, 0x5f, 0xd9, 0xc1, 0xdb, 0xdc, 0xbd, 0x84,
	0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xbb, 0xb9, 0xfd, 0x1c, 0x02, 0x00, 0x00,
}
